site_name: Wro.cpp
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  font:
    text: Quicksand
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: #3EB5E9
      accent: #EA541E
    - scheme: slate
      toggle: 
        icon: material/toggle-switch
        name: Switch to light mode
      primary: #3EB5E9
      accent: #414142

extra:
  social: 
    - icon: fontawesome/brands/github-alt
      link: https://github.com/wrocpp/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/wrocpp
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/wro-cpp

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html

copyright: |
  &copy; 2024 <a href="https://github.com/wrocpp/" target="_blank" rel="noopener">Wro.cpp Community</a>
